### ISSUE TITLE
unknown mods found by JohnM514

### ISSUE THREAD

**Issue by JohnM514** [shakeyourbunny/RWMSDB#462] opened 2019-09-04 05:32 UTC
{
 "meta": {
  "contributor": "JohnM514",
  "mods_known": 40,
  "mods_unknown": 1,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.95.1",
  "time": "Tue Sep  3 23:32:07 2019"
 },
 "unknown": {
  "Animals Are Fun": [
   "not_categorized",
   "<RimWorld install directory>\\Mods\\Animals Are Fun"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment] 2019-09-08 08:12
duplicate of #460

**Closed by shakeyourbunny** 2019-09-08 08:12 UTC
Labels: duplicate
