### ISSUE TITLE
unknown mods found by Eruestani

### ISSUE THREAD

**Issue by Eruestani** [shakeyourbunny/RWMSDB#396] opened 2019-08-18 21:34 UTC
{
 "meta": {
  "contributor": "Eruestani",
  "mods_known": 635,
  "mods_unknown": 2,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.95.1",
  "time": "Sun Aug 18 22:34:56 2019"
 },
 "unknown": {
  "RimJobWorld: Questionable Ethics": [
   "not_categorized",
   "<RimWorld install directory>\\Mods\\RimJobWorld_QuestionableEthics"
  ],
  "RimNudeWorld": [
   "not_categorized",
   "<RimWorld install directory>\\Mods\\RimNudeWorld"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment] 2019-08-24 13:47
duplicate of #397

**Closed by shakeyourbunny** 2019-08-24 13:47 UTC
Labels: duplicate
