### ISSUE TITLE
unknown mods found by LemmysTash

### ISSUE THREAD

**Issue by LemmysTash** [shakeyourbunny/RWMSDB#165] opened 2019-06-01 20:03 UTC
{
 "meta": {
  "contributor": "LemmysTash",
  "mods_known": 117,
  "mods_unknown": 1,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.94.6",
  "time": "Sat Jun  1 21:03:52 2019"
 },
 "unknown": {
  "Boomalope fix [CE+SW]": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1680564537"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment] 2019-06-02 14:15
Hi,

duplicate of #163

**Closed by shakeyourbunny** 2019-06-02 14:15 UTC
Labels: duplicate

**Comment by LemmysTash** [comment] 2019-06-14 09:43
Hey man, i dunno if i can reply to this email or i should shout you
somewhere else. I only signed up for Github so i could help with sending
data for the mod and i have no idea how any of it works.
If I get conflics between mods i know work together after using your mod,
should i send you the error/conflic log or is that not something you'd want
bothered with?

Your mod is a lifesaver for me dude. Thanks for your work.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by shakeyourbunny** [comment] 2019-06-18 09:08
Yes, please.

If you have any mods which are not known to RWMS, please submit the unknown file.. and if there are some problems in the load order, I'll look into it and fix the problem, just send it here :-)
