### ISSUE TITLE
unknown mods found by LemmysTash

### ISSUE THREAD

**Issue by LemmysTash** [shakeyourbunny/RWMSDB#158] opened 2019-05-31 14:57 UTC
{
 "meta": {
  "contributor": "LemmysTash",
  "mods_known": 116,
  "mods_unknown": 1,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.94.6",
  "time": "Fri May 31 15:57:56 2019"
 },
 "unknown": {
  "Boomalope fix [CE+SW]": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1680564537"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment] 2019-06-02 13:58
duplicate of #160

**Closed by shakeyourbunny** 2019-06-02 13:58 UTC
