### ISSUE TITLE
unknown mods found by Radical-Dragon

### ISSUE THREAD

**Issue by Radical-Dragon** [shakeyourbunny/RWMSDB#71] opened 2019-05-05 18:28 UTC
{
 "meta": {
  "contributor": "Radical-Dragon",
  "mods_known": 146,
  "mods_unknown": 15,
  "os": "win32",
  "rimworld_version": "1.0.2231 rev1144",
  "rwms_version": "0.94.2",
  "time": "Sun May  5 13:28:35 2019"
 },
 "unknown": {
  "Expanded Patchleather v0.14": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1633551678"
  ],
  "Garden Box 1.1": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1615545604"
  ],
  "Melody Through Power!": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1206252020"
  ],
  "Silts Additional Additions": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1566065113"
  ],
  "Silts LEDs": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1472813616"
  ],
  "Simple Chains: Lumber": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1708709952"
  ],
  "Simple Shelter (from CP Srv Add)": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1693004996"
  ],
  "Snare Trap (from CP Srv Add)": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1697671530"
  ],
  "Tropi[CKAPP] Rainforest Mod": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1110093272"
  ],
  "Universal Bricks": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1560800236"
  ],
  "[1.0] Combat Shields": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1588616696"
  ],
  "[1.0] Defenses Expanded": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1550972678"
  ],
  "[N17] Thaumrim": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1567775191"
  ],
  "\u30101.0\u3011Animal straw bed": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1416347393"
  ],
  "\u3010ZP\u3011Sengoku period": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1639686421"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment] 2019-05-05 19:16
duplicate of https://github.com/shakeyourbunny/RWMSDB/issues/72

**Closed by shakeyourbunny** 2019-05-05 19:16 UTC
Labels: duplicate
