### ISSUE TITLE
unknown mods found by melvingroenendaal@gmail.com

### ISSUE THREAD

**Issue by MelvinGr** [shakeyourbunny/RWMSDB#302] opened 2019-07-19 16:04 UTC
{
 "meta": {
  "contributor": "melvingroenendaal",
  "mods_known": 269,
  "mods_unknown": 8,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.94.7",
  "time": "Fri Jul 19 18:04:04 2019"
 },
 "unknown": {
  "Animal Hoods": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1803983521"
  ],
  "CUSTOM": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Custom"
  ],
  "FemaleBB BodyType Support": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1792668502"
  ],
  "Oni of the Rim: Lite": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1807327083"
  ],
  "Self Lovin": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1683469057"
  ],
  "Table 1x1": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1719914896"
  ],
  "The Birds and the Bees EPOE Patch": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1802776034"
  ],
  "Tribal know nothing": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=913240446"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment] 2019-07-27 09:55
duplicate of #301

**Closed by shakeyourbunny** 2019-07-27 09:55 UTC
Labels: duplicate
