### ISSUE TITLE
unknown mods 4/24

### ISSUE THREAD

**Issue by BlackGoatPC** [shakeyourbunny/RWMSDB#20] opened 2019-04-25 14:35 UTC
[rwms_unknown_mods_20190424-1533.json.txt](https://github.com/shakeyourbunny/RWMSDB/files/3117407/rwms_unknown_mods_20190424-1533.json.txt)

**Comment by shakeyourbunny** [comment] 2019-04-25 19:44
duplicate of https://github.com/shakeyourbunny/RWMSDB/issues/31

**Closed by shakeyourbunny** 2019-04-25 19:44 UTC
Labels: duplicate
