### ISSUE TITLE
unknown mods found by Marcopk

### ISSUE THREAD

**Issue by Marcopk** [shakeyourbunny/RWMSDB#214] opened 2019-06-13 19:36 UTC
{
 "meta": {
  "contributor": "Marcopk",
  "mods_known": 236,
  "mods_unknown": 12,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.94.6",
  "time": "Thu Jun 13 16:36:22 2019"
 },
 "unknown": {
  "Apex: Rimworld Legends test": [
   "not_categorized",
   ""
  ],
  "Bulk Stone Cutting": [
   "not_categorized",
   ""
  ],
  "Bulk craft": [
   "not_categorized",
   ""
  ],
  "Carry Capacity Fix": [
   "not_categorized",
   ""
  ],
  "Infectious Creatures 1.0": [
   "not_categorized",
   ""
  ],
  "Mass Cooking": [
   "not_categorized",
   ""
  ],
  "Mo' Drugs": [
   "not_categorized",
   ""
  ],
  "No Death Cooties On Armour": [
   "not_categorized",
   ""
  ],
  "No More Missing Fingers - A Combat Overhaul": [
   "not_categorized",
   ""
  ],
  "[1.0] More Lamps Always on": [
   "not_categorized",
   ""
  ],
  "[1.0] RimWorld Rabbids V2.0": [
   "not_categorized",
   ""
  ],
  "[1.0] Wild Animal Sex V4.0": [
   "not_categorized",
   ""
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment] 2019-06-15 19:52
duplicate of #209

**Closed by shakeyourbunny** 2019-06-15 19:52 UTC
