### ISSUE TITLE
unknown mods found by pigand

### ISSUE THREAD

**Issue by pigand** [shakeyourbunny/RWMSDB#106] opened 2019-05-15 06:51 UTC
{
 "meta": {
  "contributor": "pigand",
  "mods_known": 443,
  "mods_unknown": 88,
  "os": "win32",
  "rimworld_version": "1.0.2231 rev1144",
  "rwms_version": "0.94.5",
  "time": "Tue May 14 23:51:17 2019"
 },
 "unknown": {
  "Adaptation Refusal": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Adaptation Refusal"
  ],
  "All The Doormats": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=All The Doormats"
  ],
  "Anesthetic Turret Mod[1.0]": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Anesthetic Turret Mod[1.0]"
  ],
  "Area Rugs for 1.0": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Area Rugs for 1.0"
  ],
  "Arrow Please": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Arrow Please"
  ],
  "Better vents": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Better vents 1.0"
  ],
  "Biomatter (B19 Edition)": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Biomatter B19 Edition"
  ],
  "Cactaceae": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Cactaceae"
  ],
  "Caution Tiles [1.0]": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Caution Tiles"
  ],
  "Character Editor": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Character Editor"
  ],
  "Chemfuel Cage": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Chemfuel Cage"
  ],
  "Chemfuel burners": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=[TX] Chemfuel burners"
  ],
  "Clutter \"The Door Stuff\"": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Clutter Structure_doorStuff"
  ],
  "Clutter \"Windows Stuff\"": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Clutter Structure_Windows_Mod"
  ],
  "Clutter Structures": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Clutter Structure"
  ],
  "Colourful Sterile Tiles": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Colourful Sterile Tiles"
  ],
  "Copyprint": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Copyprint"
  ],
  "Cryptorestore Caskets (1.0)": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Cryptorestore Caskets"
  ],
  "Dress Patients": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Dress Patients"
  ],
  "Duct Tape!": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Duct Tape!"
  ],
  "Electric Igniter": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Electric Igniter"
  ],
  "Enhanced Door": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Enhanced Door"
  ],
  "FFSmilodon caravaneer": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=FFSmilodon caravaneer"
  ],
  "Frontline - Trenches without guns": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=+_1_0_Frontline_Trenches_without_guns"
  ],
  "Gone with the Rimwave - (1.0)": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Gone with the Rimwave - (1.0)"
  ],
  "Grenades Expanded": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Grenades Expanded"
  ],
  "Imp Race 1.0": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Imp Race"
  ],
  "InwallShelf": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=InwallShelf"
  ],
  "Jecs Tobacco and Cigarettes": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Jecs Tobacco and Cigarettes"
  ],
  "Jello People": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Jello People"
  ],
  "Jernfalk's Paper Currency Mod": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=[1.0] Jernfalk's Paper Currency Mod"
  ],
  "KK_ACCTG!": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Anyone Can Craft Tribal Gears!"
  ],
  "LED Lights": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=LED Lights"
  ],
  "Lazy Base Lighting": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Lazy Base Lighting"
  ],
  "Mechanical Defense 2 - base": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Mechanical Defense 2 - base"
  ],
  "Mechanical Defense 2 - mechanical walls": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Mechanical Defense 2 - mechanical walls"
  ],
  "Medical IV": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Medical IV"
  ],
  "Melee Please": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Melee Please"
  ],
  "Meteors": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Meteors"
  ],
  "MoD's Mods - Docile Hive": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=MoD's Mods - Docile Hive"
  ],
  "More Higher difficulty": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=More Higher difficulty"
  ],
  "More Lances": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=More Lances"
  ],
  "Mutants": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Mutants"
  ],
  "No Random Breakdown + No Random Shortcircruit": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=No_Random_Breakdown_plus_No Random_Shortcircruit"
  ],
  "No Self Tame": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=No Self Tame"
  ],
  "Nuke's Drug Cocktails": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Nuke's Drug Cocktails"
  ],
  "Nutrient Paste Rebalanced": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Nutrient Paste Rebalanced"
  ],
  "Old Gods - Music": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Old Gods - Music"
  ],
  "Penoxycyline for food poisoning": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Penoxycyline for food poisoning"
  ],
  "Plant Milk": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Plant Milk"
  ],
  "Plasma Weaponry": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Plasma Weaponry"
  ],
  "Proper Beavers 1.0": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Proper Beavers 1.0"
  ],
  "RD - Slow Down": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=RD - Slow Down"
  ],
  "RWS Compressor": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=RWS Compressor"
  ],
  "Rimica": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Rimica"
  ],
  "Rimmunizations": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Rimmunizations"
  ],
  "Rimoprene": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Rimoprene"
  ],
  "Rimworld Westernization Project": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Rimworld Westernization Project"
  ],
  "Select Turret Target": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Selectable Turret Target"
  ],
  "Server": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Server"
  ],
  "Simple Pathfinding": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Simple Pathfinding"
  ],
  "Slave Outfits [1.0]": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Slave Outfits [1.0]"
  ],
  "SoundSystem": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=+_TX_SoundSystem"
  ],
  "Steel Foam": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Steel Foam"
  ],
  "Stone Dining Chairs": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Stone Dining Chairs"
  ],
  "Straw Floor [A18]": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Straw Floor [B18]"
  ],
  "Supply Drop!": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Supply Drop!"
  ],
  "Sustainable Drill Updated": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Sustainable Drill [1.0]"
  ],
  "The Mantodean insectoid race": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=The Mantodean insectoid race"
  ],
  "Torgue": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Torgue"
  ],
  "Tree People": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Tree People"
  ],
  "Underground Conduits": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Underground Conduits"
  ],
  "Warm and Cool FloorPaint [1.0]": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Warm and Cool FloorPaint [1.0]"
  ],
  "Wax Stuff": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Wax Stuff"
  ],
  "Weaponry": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Weaponry"
  ],
  "White only": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=White only"
  ],
  "XUV flares": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=XUV flares"
  ],
  "ZARS Simple Fish": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=ZARS Simple Fish"
  ],
  "[1.0 | JAM] Brad's Plaid! (v1.0.2)": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=[1.0  JAM] Brad's Plaid! (v1.0.2)"
  ],
  "[1.0] Hunting Rifle + Sports Shotgun Series Pack": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=[1.0] Hunting Rifle + Sports Shotgun Series Pack"
  ],
  "[1.0]Chemical Weather": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=[1.0]Chemical Weather"
  ],
  "[1.0]Mystery Meat: Feed human meat to colonists!": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=[1.0]Mystery Meat Feed human meat to colonists!"
  ],
  "[C81] Canned food": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=+_C81_Canned_food"
  ],
  "[Core] MDK Terrain Patch": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=+_Core_MDK_Terrain_Patch"
  ],
  "[Ling]Cooler1.0": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=[Ling]Cooler1.0"
  ],
  "[MS-I] Brain surgery": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=+_MS_I_Brain_surgery"
  ],
  "[SimplySublime] - ABS Polymer": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=+SimplySublime_ABS_Polymer_B19"
  ],
  "[sd] pillows and beanbags": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=[sd] pillows and beanbags"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment] 2019-05-16 09:39
duplicate of https://github.com/shakeyourbunny/RWMSDB/issues/110

**Closed by shakeyourbunny** 2019-05-16 09:39 UTC
Labels: duplicate
