### ISSUE TITLE
unknown mods found by JangeL1997

### ISSUE THREAD

**Issue by JangeL1997** [shakeyourbunny/RWMSDB#293] opened 2019-07-17 12:05 UTC
{
 "meta": {
  "contributor": "JangeL1997",
  "mods_known": 197,
  "mods_unknown": 3,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.94.7",
  "time": "Wed Jul 17 20:05:10 2019"
 },
 "unknown": {
  "Carry Capacity Fix": [
   "not_categorized",
   ""
  ],
  "Chanfana's Things: GD edition": [
   "not_categorized",
   ""
  ],
  "Rimsenal: Marauders": [
   "not_categorized",
   ""
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment] 2019-07-17 16:33
duplicate of https://github.com/shakeyourbunny/RWMSDB/issues/292

**Closed by shakeyourbunny** 2019-07-17 16:33 UTC
Labels: duplicate
