### ISSUE TITLE
unknown mods found by aboleba

### ISSUE THREAD

**Issue by aboleba** [shakeyourbunny/RWMSDB#328] opened 2019-07-29 14:37 UTC
{
 "meta": {
  "contributor": "aboleba",
  "mods_known": 270,
  "mods_unknown": 4,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.94.7",
  "time": "Mon Jul 29 10:37:43 2019"
 },
 "unknown": {
  "Trench Cats": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1788733617"
  ],
  "Vanilla Apparel Expanded": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1814987817"
  ],
  "Vanilla Armour Expanded": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1814988282"
  ],
  "Vanilla Weapons Expanded": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1814383360"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment] 2019-07-30 18:25
duplicate of #326

**Closed by shakeyourbunny** 2019-07-30 18:25 UTC
Labels: duplicate
