### ISSUE TITLE
unknown mods found by randomnone

### ISSUE THREAD

**Issue by randomnone** [shakeyourbunny/RWMSDB#231] opened 2019-06-21 07:13 UTC
{
 "meta": {
  "contributor": "randomnone",
  "mods_known": 2,
  "mods_unknown": 7,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.94.6",
  "time": "Fri Jun 21 00:13:18 2019"
 },
 "unknown": {
  "Children and Pregnancy - Jarry1250": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=ChildrenAndPregnancy-master"
  ],
  "Children and Pregnancy - Testing v0.3k": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=ChildrenMod"
  ],
  "RimJobWorld[B19]": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=RJW"
  ],
  "Rimjobworld": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=RJW-1.5.4j atf edit"
  ],
  "Romance Tweaks+ 2019-01-04": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=RomanceTweaksPlus"
  ],
  "Tobe's Dining Room": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Tobe's Dining Room_11_2"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment] 2019-06-23 06:56
duplicate of https://github.com/shakeyourbunny/RWMSDB/issues/230

**Closed by shakeyourbunny** 2019-06-23 06:56 UTC
Labels: duplicate
