### ISSUE TITLE
unknown mods found by spacedestructor

### ISSUE THREAD

**Issue by Spacedestructor** [shakeyourbunny/RWMSDB#585] opened 2019-09-23 14:03 UTC
{
 "meta": {
  "contributor": "spacedestructor",
  "mods_known": 2,
  "mods_unknown": 12,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.95.1",
  "time": "Mon Sep 23 16:03:09 2019"
 },
 "unknown": {
  "Carboplas Armor": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1418672456"
  ],
  "Gloomy Deco": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1865654125"
  ],
  "Makeable Artifacts": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1735019889"
  ],
  "NonDecayingStorage": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=736583793"
  ],
  "Power of Energy": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1547777789"
  ],
  "Replacement Organ Crafting": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=736584014"
  ],
  "Royal Thrumbos": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1865990377"
  ],
  "Temperature Control": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=736584236"
  ],
  "[O21] Elves": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1865535554"
  ],
  "[O21] Elves: Faction Addon": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1867068679"
  ],
  "[O21] Goblins": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1863617520"
  ],
  "[O21] Goblins: Faction Addon": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1867068456"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment] 2019-10-12 09:54
duplicate of #586

**Closed by shakeyourbunny** 2019-10-12 09:54 UTC
