### ISSUE TITLE
unknown mods found by SpookieWookie

### ISSUE THREAD

**Issue by SpookieWookie** [shakeyourbunny/RWMSDB#442] opened 2019-08-26 18:35 UTC
{
 "meta": {
  "contributor": "SpookieWookie",
  "mods_known": 149,
  "mods_unknown": 1,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.95.1",
  "time": "Mon Aug 26 19:35:27 2019"
 },
 "unknown": {
  "Vanilla Furniture Expanded: Security": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1845154007"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment] 2019-08-31 07:05
duplicate of #440

**Closed by shakeyourbunny** 2019-08-31 07:05 UTC
