### ISSUE TITLE
unknown mods found by JangeL1997

### ISSUE THREAD

**Issue by JangeL1997** [shakeyourbunny/RWMSDB#290] opened 2019-07-17 02:33 UTC
{
 "meta": {
  "contributor": "JangeL1997",
  "mods_known": 2,
  "mods_unknown": 1,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.94.7",
  "time": "Wed Jul 17 10:33:33 2019"
 },
 "unknown": {
  "Only a Vegetable Garden": [
   "not_categorized",
   ""
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment] 2019-07-17 16:32
duplicate of https://github.com/shakeyourbunny/RWMSDB/issues/288

**Closed by shakeyourbunny** 2019-07-17 16:32 UTC
