### ISSUE TITLE
unknown mods found by JohnM514

### ISSUE THREAD

**Issue by JohnM514** [shakeyourbunny/RWMSDB#468] opened 2019-09-05 07:02 UTC
{
 "meta": {
  "contributor": "JohnM514",
  "mods_known": 54,
  "mods_unknown": 2,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.95.1",
  "time": "Thu Sep  5 01:02:51 2019"
 },
 "unknown": {
  "ED Embrasures": [
   "not_categorized",
   "<RimWorld install directory>\\Mods\\ED Embrasures"
  ],
  "Runtime GC": [
   "not_categorized",
   "<RimWorld install directory>\\Mods\\Runtime GC"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment] 2019-09-08 08:17
duplicate of #466

**Closed by shakeyourbunny** 2019-09-08 08:17 UTC
