### ISSUE TITLE
unknown mods found by Marcopk

### ISSUE THREAD

**Issue by Marcopk** [shakeyourbunny/RWMSDB#212] opened 2019-06-13 18:48 UTC
{
 "meta": {
  "contributor": "Marcopk",
  "mods_known": 19,
  "mods_unknown": 2,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.94.6",
  "time": "Thu Jun 13 15:48:14 2019"
 },
 "unknown": {
  "Bulk craft": [
   "not_categorized",
   ""
  ],
  "[1.0] RimWorld Rabbids V2.0": [
   "not_categorized",
   ""
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment] 2019-06-15 19:51
duplicate of #209

**Closed by shakeyourbunny** 2019-06-15 19:51 UTC
