### ISSUE TITLE
unknown mods found by Egor-Mikhaylov

### ISSUE THREAD

**Issue by Egor-Mikhaylov** [shakeyourbunny/RWMSDB#550] opened 2019-09-16 23:37 UTC
{
 "meta": {
  "contributor": "Egor-Mikhaylov",
  "mods_known": 241,
  "mods_unknown": 2,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.95.1",
  "time": "Mon Sep 16 18:37:21 2019"
 },
 "unknown": {
  "MonoRocks": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=MonoRocks"
  ],
  "Tick MultiThread": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=TickMultiThread"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment] 2019-09-26 13:37
duplicate of #534

**Closed by shakeyourbunny** 2019-09-26 13:37 UTC
