### ISSUE TITLE
unknown mods found by kladdey

### ISSUE THREAD

**Issue by Kladdey** [shakeyourbunny/RWMSDB#61] opened 2019-05-04 10:53 UTC
{
 "No debuffs from pet killing\\selling": [
  "not_categorized",
  "https://steamcommunity.com/sharedfiles/filedetails/?id=733364255"
 ],
 "_meta": {
  "contributor": "kladdey",
  "mods_known": 113,
  "mods_unknown": 1,
  "os": "win32",
  "rimworld_version": "1.0.2231 rev1144",
  "rwms_version": "0.94.1",
  "time": "Sat May  4 12:53:15 2019"
 },
 "_version": 2
}

**Comment by shakeyourbunny** [comment] 2019-05-04 11:30
duplicate of https://github.com/shakeyourbunny/RWMSDB/issues/59

**Closed by shakeyourbunny** 2019-05-04 11:30 UTC
Labels: duplicate
