### ISSUE TITLE
unknown mods found by LemmysTash

### ISSUE THREAD

**Issue by LemmysTash** [shakeyourbunny/RWMSDB#204] opened 2019-06-12 23:46 UTC
{
 "meta": {
  "contributor": "LemmysTash",
  "mods_known": 152,
  "mods_unknown": 2,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.94.6",
  "time": "Thu Jun 13 00:46:12 2019"
 },
 "unknown": {
  "More Events Mod [CE Patch]": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1760755314"
  ],
  "RT's Weapon Pack CE Version [1.0]": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1763493575"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment] 2019-06-15 19:45
duplicate of #202

**Closed by shakeyourbunny** 2019-06-15 19:45 UTC
Labels: duplicate
