### ISSUE TITLE
unknown mods found by JamesTalon

### ISSUE THREAD

**Issue by JamesTalon** [shakeyourbunny/RWMSDB#449] opened 2019-08-29 23:00 UTC
{
 "meta": {
  "contributor": "JamesTalon",
  "mods_known": 184,
  "mods_unknown": 7,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.95.1",
  "time": "Thu Aug 29 19:00:29 2019"
 },
 "unknown": {
  "Bad Traits Improvement": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1838574873"
  ],
  "Dragonian Race Factions and Scenarios": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1817690190"
  ],
  "Kenshi Hiver Race": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1840737944"
  ],
  "Kenshi Skeleton Race": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1841876651"
  ],
  "SRTS": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1833992261"
  ],
  "SRTS Expanded": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1845423808"
  ],
  "[CP] I Need Nourishment!: Slower Malnutrition": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1842663403"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment] 2019-08-31 07:15
seems to be a dupe of the recent submission, all are added now, though.

**Closed by shakeyourbunny** 2019-08-31 07:15 UTC
