### ISSUE TITLE
unknown mods found by LemmysTash

### ISSUE THREAD

**Issue by LemmysTash** [shakeyourbunny/RWMSDB#207] opened 2019-06-13 07:28 UTC
{
 "meta": {
  "contributor": "LemmysTash",
  "mods_known": 174,
  "mods_unknown": 4,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.94.6",
  "time": "Thu Jun 13 08:28:13 2019"
 },
 "unknown": {
  "1.0 - ACP - More Floors Wool Patch": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1766524688"
  ],
  "Cybernetic Organism and Neural Network": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1767214408"
  ],
  "More Events Mod [CE Patch]": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1760755314"
  ],
  "RT's Weapon Pack CE Version [1.0]": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1763493575"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment] 2019-06-15 19:47
sorta duplicate of #202

**Comment by shakeyourbunny** [comment] 2019-06-15 20:07
added your contribution, thank you.

**Closed by shakeyourbunny** 2019-06-15 20:07 UTC
