### ISSUE TITLE
unknown mods found by Toby-Lawrance

### ISSUE THREAD

**Issue by Toby-Lawrance** [shakeyourbunny/RWMSDB#170] opened 2019-06-03 21:23 UTC
{
 "meta": {
  "contributor": "Toby-Lawrance",
  "mods_known": 151,
  "mods_unknown": 1,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.94.6",
  "time": "Mon Jun  3 22:23:16 2019"
 },
 "unknown": {
  "Real Fog of War Extended": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1756856110"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment] 2019-06-05 19:34
duplicate of #169

**Closed by shakeyourbunny** 2019-06-05 19:34 UTC
Labels: duplicate
