### ISSUE TITLE
unknown mods found by JangeL1997

### ISSUE THREAD

**Issue by JangeL1997** [shakeyourbunny/RWMSDB#180] opened 2019-06-05 06:16 UTC
{
 "meta": {
  "contributor": "JangeL1997",
  "mods_known": 3,
  "mods_unknown": 2,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.94.6",
  "time": "Wed Jun  5 14:16:55 2019"
 },
 "unknown": {
  "Desynchronized: Tales and News (v1.5.3)": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1573233249"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment] 2019-06-05 19:53
duplicate of #179

**Closed by shakeyourbunny** 2019-06-05 19:53 UTC
Labels: duplicate
