### ISSUE TITLE
unknown mods found by Deathawaits4

### ISSUE THREAD

**Issue by Deathawaits4** [shakeyourbunny/RWMSDB#66] opened 2019-05-05 02:07 UTC
{
 "Better Infestations 1.0": "not_categorized",
 "_contributor": "Deathawaits4",
 "time": "Sun May  5 04:07:28 2019"
}

**Comment by shakeyourbunny** [comment] 2019-05-05 08:43
duplicate of https://github.com/shakeyourbunny/RWMSDB/issues/65

**Closed by shakeyourbunny** 2019-05-05 08:43 UTC
Labels: duplicate
