### ISSUE TITLE
unknown mods found by aboleba

### ISSUE THREAD

**Issue by aboleba** [shakeyourbunny/RWMSDB#306] opened 2019-07-19 22:49 UTC
{
 "meta": {
  "contributor": "aboleba",
  "mods_known": 231,
  "mods_unknown": 5,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.94.7",
  "time": "Fri Jul 19 18:49:14 2019"
 },
 "unknown": {
  "Deadly Weapon Tweaks": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=824659667"
  ],
  "Drop on Water Revived": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1807530429"
  ],
  "EPOE: Trader and Archotech patch": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1800828478"
  ],
  "Melee Weapons Rebalance": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1644122271"
  ],
  "VERY ACCURATE HUMAN DEATH SOUND": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1525395481"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment] 2019-07-27 10:09
duplicate of #305

**Closed by shakeyourbunny** 2019-07-27 10:09 UTC
Labels: duplicate
