### ISSUE TITLE
unknown mods found by MlTHRlL

### ISSUE THREAD

**Issue by MlTHRlL** [shakeyourbunny/RWMSDB#432] opened 2019-08-24 21:32 UTC
{
 "meta": {
  "contributor": "MlTHRlL",
  "mods_known": 226,
  "mods_unknown": 2,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.95.1",
  "time": "Sun Aug 25 02:32:46 2019"
 },
 "unknown": {
  "Multiplayer-able Glue": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1804480342"
  ],
  "WearedArmorInfo": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1839305669"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment] 2019-08-30 21:10
duplicate of #431

**Closed by shakeyourbunny** 2019-08-30 21:10 UTC
