### ISSUE TITLE
unknown mods found by questionmarkexclamationpoint

### ISSUE THREAD

**Issue by questionmarkexclamationpoint** [shakeyourbunny/RWMSDB#317] opened 2019-07-25 20:09 UTC
{
 "meta": {
  "contributor": "questionmarkexclamationpoint",
  "mods_known": 190,
  "mods_unknown": 9,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.94.7",
  "time": "Thu Jul 25 13:09:23 2019"
 },
 "unknown": {
  "All The Doormats": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=__LocalCopy_All The Doormats_(14-5)"
  ],
  "Animal Gear Rhino": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=__LocalCopy_Animal Gear Rhino_(14-5)"
  ],
  "Faster Smoothing": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=__LocalCopy_Faster Smoothing_(25-7)"
  ],
  "Orcs": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=__LocalCopy_Orcs_(20-5)"
  ],
  "[XND] Rename Your Weapons!": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=__LocalCopy_[XND] Rename Your Weapons!_(25-7)"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment] 2019-07-27 10:23
duplicate of #316

**Closed by shakeyourbunny** 2019-07-27 10:23 UTC
Labels: duplicate
