### ISSUE TITLE
unknown mods found by Sixbooy

### ISSUE THREAD

**Issue by Sixbooy** [shakeyourbunny/RWMSDB#538] opened 2019-09-16 00:40 UTC
{
 "meta": {
  "contributor": "Sixbooy",
  "mods_known": 193,
  "mods_unknown": 2,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.95.1",
  "time": "Mon Sep 16 02:40:28 2019"
 },
 "unknown": {
  "Combat Enthusiast's Collection": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1862509294"
  ],
  "Jin-Roh Kerberos Panzer Cop Armor": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1861644030"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment] 2019-09-26 13:44
duplicate of #537

**Closed by shakeyourbunny** 2019-09-26 13:44 UTC
