### ISSUE TITLE
unknown mods found by AerosolNinja

### ISSUE THREAD

**Issue by AerosolNinja** [shakeyourbunny/RWMSDB#710] opened 2019-10-17 03:05 UTC
{
 "meta": {
  "contributor": "AerosolNinja",
  "mods_known": 224,
  "mods_unknown": 3,
  "os": "win32",
  "rimworld_version": "1.0.2408 rev747",
  "rwms_version": "0.95.1",
  "time": "Wed Oct 16 20:05:11 2019"
 },
 "unknown": {
  "Optimization: RAID": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1885551217"
  ],
  "Preemptive Strike": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1890377807"
  ],
  "Vanilla Hair Expanded": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1888705256"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment] 2019-10-19 18:06
duplicate of #712

**Closed by shakeyourbunny** 2019-10-19 18:06 UTC
Labels: duplicate
