### ISSUE TITLE
unknown mods found by Egor-Mikhaylov

### ISSUE THREAD

**Issue by Egor-Mikhaylov** [shakeyourbunny/RWMSDB#496] opened 2019-09-08 23:31 UTC
{
 "meta": {
  "contributor": "Egor-Mikhaylov",
  "mods_known": 296,
  "mods_unknown": 4,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.95.1",
  "time": "Sun Sep  8 18:31:10 2019"
 },
 "unknown": {
  "Idle Pawn Fix": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=IdleFix"
  ],
  "MonoRocks": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=MonoRocks"
  ],
  "Rimsenal: Enhanced Vanilla Pack CE Patch": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=Rimsenal - Enhanced Vanilla Pack CE Patch"
  ],
  "[test] Star Wars Factions + CE compatibility patch (b18)": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=CEPatchSWF-master"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment] 2019-09-14 07:13
duplicate of #494

**Closed by shakeyourbunny** 2019-09-14 07:13 UTC
