### ISSUE TITLE
unknown mods found by lolidroid86@gmail.com

### ISSUE THREAD

**Issue by lolidroid86** [shakeyourbunny/RWMSDB#285] opened 2019-07-13 13:41 UTC
{
 "meta": {
  "contributor": "lolidroid86",
  "mods_known": 252,
  "mods_unknown": 9,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.94.7",
  "time": "Sat Jul 13 09:41:35 2019"
 },
 "unknown": {
  "Cannibal Meals (VGP required)": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1537104826"
  ],
  "Craft Orbital Power Beam Targeter and Orbital Targeter Bombardment": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1661329973"
  ],
  "Planetary Drill+": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1788136410"
  ],
  "Rapid fire turret .": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1524537370"
  ],
  "Sharknado": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1545122241"
  ],
  "Small Nutrient Paste Dispenser": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=842875898"
  ],
  "Star Trek: Races": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1641944043"
  ],
  "Unbalanced Stuff: Adamantine": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1103159143"
  ],
  "\u304a\u3063\u3071\u3044\u8ffd\u52a0": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1235378064"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment] 2019-07-14 15:13
duplicate of https://github.com/shakeyourbunny/RWMSDB/issues/285

**Closed by shakeyourbunny** 2019-07-14 15:13 UTC
