### ISSUE TITLE
unknown mods found by zavian

### ISSUE THREAD

**Issue by Zavian** [shakeyourbunny/RWMSDB#379] opened 2019-08-12 23:18 UTC
{
 "meta": {
  "contributor": "zavian",
  "mods_known": 209,
  "mods_unknown": 4,
  "os": "win32",
  "rimworld_version": "1.0.2282 rev726",
  "rwms_version": "0.94.7",
  "time": "Tue Aug 13 01:18:47 2019"
 },
 "unknown": {
  "Dragonkin": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1793932198"
  ],
  "Mercenaries For Me": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1832318107"
  ],
  "Vanilla Floors Tweaked": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1727373705"
  ],
  "Wall Mounted Turrets": [
   "not_categorized",
   "https://steamcommunity.com/sharedfiles/filedetails/?id=1812077718"
  ]
 },
 "version": 2
}

**Comment by shakeyourbunny** [comment] 2019-08-18 17:56
duplicate of #378

**Closed by shakeyourbunny** 2019-08-18 17:56 UTC
