### ISSUE TITLE
unknown mods found by djhardy1990@gmail.com

### ISSUE THREAD

**Issue by Victaria90** [shakeyourbunny/RWMSDB#37] opened 2019-04-27 16:04 UTC
{
 "All for One [1.0]": "not_categorized",
 "Boulder Trap Mod": "not_categorized",
 "Call of Cthulhu - Elder Things Tweak": "not_categorized",
 "Children and Pregnancy - v0.5a": "not_categorized",
 "Clear The Stockpiles": "not_categorized",
 "ClutterDoors": "not_categorized",
 "Combat Extended Guns Retextured": "not_categorized",
 "Compact Benches": "not_categorized",
 "Cyber Fauna 1.0": "not_categorized",
 "Designator Shapes": "not_categorized",
 "Dinosauria Unoffical CE Patch": "not_categorized",
 "Dubs Skylights Glass+Lights Patch": "not_categorized",
 "ETRT: Cannibal Tweaks": "not_categorized",
 "Extended Storage RimCuisine Patch": "not_categorized",
 "Extra Traits for CE": "not_categorized",
 "Fire Warden": "not_categorized",
 "Fishing Nets": "not_categorized",
 "Frontline - Bunkers CE Version": "not_categorized",
 "Frontline - Trenches CE Version": "not_categorized",
 "Fueled Smelter": "not_categorized",
 "Generic CE Ammo": "not_categorized",
 "Genetic Rim Dinosauria CE Patch": "not_categorized",
 "Gimmicks": "not_categorized",
 "Hardcore Fertile Fields": "not_categorized",
 "Harvest Sync": "not_categorized",
 "Improved Infestation": "not_categorized",
 "LOTR and Bones": "not_categorized",
 "Lighter Colorful Traits": "not_categorized",
 "Lizardmen Lite": "not_categorized",
 "Medieval Bones": "not_categorized",
 "Medieval Times Balance Patch (CE version)": "not_categorized",
 "Megafauna (CE compatibility patch)": "not_categorized",
 "Mercer's Backpacks (B19)": "not_categorized",
 "MizuModAddon\u3010ZP\u3011RCC\u30101.0\u3011": "not_categorized",
 "Muh Eggs! [1.0]": "not_categorized",
 "NightVision": "not_categorized",
 "Optimization: CE Ammo": "not_categorized",
 "Optimization: Meats": "not_categorized",
 "Ore processing": "not_categorized",
 "Pawns Paint! Restored": "not_categorized",
 "RPG Style Inventory CE Patch": "not_categorized",
 "RS Horse Armor and Saddles for Animal Gear": "not_categorized",
 "RS Patch for RimFace (Facial Stuff Version)": "not_categorized",
 "RePower EPOE Patch": "not_categorized",
 "RePower HighTech Laboratory Facilities Patch": "not_categorized",
 "RePower Rimatomics Patch": "not_categorized",
 "Rimsenal + Combat Extended Compatibility Patch": "not_categorized",
 "SeedsPleaseAddon\u3010ZP\u3011RCC\u30101.0\u3011": "not_categorized",
 "Sparkling Worlds - CE Patch [1.0] - Combat Extendend Compatibility": "not_categorized",
 "Tiny Workbenchs": "not_categorized",
 "To My Side! - Medieval": "not_categorized",
 "Toggle Refuelable": "not_categorized",
 "Toolmetric CE Patch": "not_categorized",
 "Uninstall Rimworld": "not_categorized",
 "[SYR] Neuter": "not_categorized",
 "_contributor": "djhardy1990@gmail.com",
 "time": "Sat Apr 27 12:04:48 2019",
 "\u3010ZP\u3011Japanese bread": "not_categorized",
 "\u3010ZP\u3011Rice cultivating civilization\u30101.0\u3011": "not_categorized"
}

**Comment by shakeyourbunny** [comment] 2019-04-28 11:40
I guess this is a duplicate of https://github.com/shakeyourbunny/RWMSDB/issues/36, same mod list here.

**Closed by shakeyourbunny** 2019-04-28 11:40 UTC
Labels: duplicate

**Comment by Victaria90** [comment] 2019-04-28 17:22
yep sorry one was self posted other was after I learned it could auto post for me
